import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Clock, CheckCircle, AlertCircle, Loader2, ArrowRight, ShieldAlert } from 'lucide-react';

const ProfessionalTestEngine: React.FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [isAuthorized, setIsAuthorized] = useState(false);
  const [loading, setLoading] = useState(true);

  // 1. GATEKEEPER: Domain-Independent Direct Access Block
  useEffect(() => {
    const verifyGatekeeper = () => {
      // Step A: Payment verification check
      const paymentData = localStorage.getItem(`payment_${id}`);
      
      // Step B: Secure Access Token check (Generated by PaymentSuccess)
      const accessToken = localStorage.getItem(`test_access_token_${id}`);

      // STRICT BLOCK: Agar payment record ya secure token missing hai
      if (!paymentData || !accessToken) {
        console.error("Security Breach: No valid session or token found.");
        navigate(`/payment/${id}`, { replace: true });
        return;
      }

      try {
        const data = JSON.parse(paymentData);
        // Only allow if status is explicitly 'success'
        if (data.status === 'success') {
          setIsAuthorized(true);
          setLoading(false);
        } else {
          navigate(`/payment/${id}`, { replace: true });
        }
      } catch (e) {
        navigate(`/payment/${id}`, { replace: true });
      }
    };

    // Delay to ensure storage is ready across subdomains
    const timer = setTimeout(verifyGatekeeper, 1000);
    return () => clearTimeout(timer);
  }, [id, navigate]);

  // TEST CONTENT (MOCK)
  const questions = [
    { id: '1', text: 'What is the time complexity of binary search?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], correctAnswer: 2 },
    { id: '2', text: 'Which data structure uses LIFO principle?', options: ['Queue', 'Stack', 'Array', 'Linked List'], correctAnswer: 1 },
    { id: '3', text: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Question Language', 'Structured Question Logic', 'Standard Query Logic'], correctAnswer: 0 },
    { id: '4', text: 'Which HTTP method is used for creating resources?', options: ['GET', 'POST', 'PUT', 'DELETE'], correctAnswer: 1 },
    { id: '5', text: 'What is the main purpose of CSS?', options: ['To add interactivity', 'To structure content', 'To style content', 'To query databases'], correctAnswer: 2 },
  ];

  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<number[]>(Array(questions.length).fill(-1));
  const [timeLeft, setTimeLeft] = useState(30 * 60);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [warningCount, setWarningCount] = useState(0);

  // ANTI-CHEAT & TIMER LOGIC
  useEffect(() => {
    if (!isAuthorized || isSubmitted) return;

    const timer = setInterval(() => {
      setTimeLeft(prev => {
        if (prev <= 1) {
          clearInterval(timer);
          handleSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    const handleVisibilityChange = () => {
      if (document.hidden && !isSubmitted) {
        setWarningCount(prev => {
          const newCount = prev + 1;
          if (newCount >= 3) {
            handleSubmit();
            alert('CRITICAL: Test auto-submitted due to security policy (tab switching).');
          } else {
            alert(`SECURITY WARNING (${newCount}/3): Stay on this page. Switching tabs will auto-submit your test.`);
          }
          return newCount;
        });
      }
    };

    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => {
      clearInterval(timer);
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, [isAuthorized, isSubmitted]);

  const handleSubmit = () => {
    let correct = 0;
    questions.forEach((q, i) => {
      if (answers[i] === q.correctAnswer) correct++;
    });
    setScore(Math.round((correct / questions.length) * 100));
    setIsSubmitted(true);
    
    // Cleanup: Remove access token after completion to prevent re-entry
    localStorage.removeItem(`test_access_token_${id}`);
  };

  const formatTime = (s: number) => `${Math.floor(s / 60)}:${(s % 60).toString().padStart(2, '0')}`;

  // Loading Overlay
  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center font-sans">
        <div className="text-center">
          <Loader2 className="w-12 h-12 text-indigo-600 animate-spin mx-auto mb-4" />
          <p className="text-slate-600 font-bold tracking-tight">Verifying Secure Session...</p>
          <p className="text-slate-400 text-xs mt-2 uppercase tracking-widest">Powered by InternAdda Shield</p>
        </div>
      </div>
    );
  }

  // Result UI
  if (isSubmitted) {
    const passed = score >= 70;
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6 font-sans">
        <div className="max-w-md w-full bg-white rounded-[40px] shadow-2xl overflow-hidden text-center p-12 border border-slate-100">
          <div className={`w-24 h-24 rounded-full mx-auto mb-8 flex items-center justify-center ${passed ? 'bg-emerald-100 text-emerald-600' : 'bg-red-100 text-red-600'}`}>
            {passed ? <CheckCircle size={48} /> : <ShieldAlert size={48} />}
          </div>
          <h1 className="text-4xl font-black text-slate-900 mb-2">{passed ? 'Qualified!' : 'Completed'}</h1>
          <div className="bg-slate-50 rounded-2xl py-6 my-8">
            <span className="text-5xl font-black text-slate-900">{score}%</span>
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-2">Final Accuracy</p>
          </div>
          <button onClick={() => navigate('/dashboard')} className="w-full bg-slate-900 hover:bg-black text-white py-5 rounded-2xl font-bold flex items-center justify-center gap-2 transition-all">
            Go to Dashboard <ArrowRight size={20} />
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0f172a] text-white font-sans selection:bg-indigo-500/30">
      {/* Secure Header */}
      <div className="bg-[#1e293b] border-b border-slate-800 px-8 py-5 flex justify-between items-center sticky top-0 z-50 backdrop-blur-md bg-opacity-80">
        <div className="flex items-center gap-4">
          <div className="bg-indigo-600 px-3 py-1 rounded text-[10px] font-black uppercase text-white tracking-tighter">Secure Session</div>
          <div className="hidden md:block">
            <div className="text-sm font-bold">Standard Professional Assessment</div>
            <div className="text-[10px] text-slate-400 uppercase font-bold tracking-widest">Gatekeeper ID: {id}</div>
          </div>
        </div>
        
        <div className="flex items-center gap-6">
          <div className={`flex items-center gap-3 px-6 py-2 rounded-xl border-2 transition-all ${timeLeft < 300 ? 'border-red-500 bg-red-500/10 animate-pulse' : 'border-slate-700 bg-slate-900'}`}>
            <Clock size={20} className={timeLeft < 300 ? 'text-red-500' : 'text-slate-400'} />
            <span className="font-mono text-2xl font-black leading-none">{formatTime(timeLeft)}</span>
          </div>
          <button 
            onClick={() => { if(window.confirm('Submit test now?')) handleSubmit(); }} 
            className="bg-emerald-600 hover:bg-emerald-500 text-white px-8 py-3 rounded-xl font-bold transition-all shadow-lg shadow-emerald-900/20"
          >
            Submit Test
          </button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto py-16 px-6">
        {warningCount > 0 && (
          <div className="mb-8 bg-red-500/10 border border-red-500/30 p-5 rounded-2xl flex items-center gap-4 text-red-400 animate-pulse">
            <AlertCircle size={24} />
            <div>
              <p className="text-sm font-black uppercase">Security Warning {warningCount}/3</p>
              <p className="text-xs font-bold opacity-80">Tab switching detected. 3rd warning will trigger auto-submission.</p>
            </div>
          </div>
        )}

        <div className="bg-[#1e293b] rounded-[40px] p-10 md:p-16 border border-slate-800 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 left-0 w-2 h-full bg-indigo-600" />
          
          <div className="mb-10">
            <span className="bg-indigo-500/10 text-indigo-400 text-[10px] font-black px-4 py-1.5 rounded-full uppercase tracking-widest border border-indigo-500/20">
              Question {currentQuestion + 1} of {questions.length}
            </span>
          </div>

          <h2 className="text-2xl md:text-4xl font-bold mb-14 leading-tight">
            {questions[currentQuestion].text}
          </h2>

          <div className="grid gap-4">
            {questions[currentQuestion].options.map((opt, idx) => (
              <button
                key={idx}
                onClick={() => {
                  const a = [...answers];
                  a[currentQuestion] = idx;
                  setAnswers(a);
                }}
                className={`w-full text-left p-6 rounded-2xl border-2 transition-all flex items-center gap-6 group ${
                  answers[currentQuestion] === idx ? 'border-indigo-500 bg-indigo-500/10' : 'border-slate-800 bg-slate-900/30 hover:border-slate-700'
                }`}
              >
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center font-bold text-xl transition-all ${
                  answers[currentQuestion] === idx ? 'bg-indigo-500 text-white' : 'bg-slate-800 text-slate-500 group-hover:bg-slate-700'
                }`}>
                  {String.fromCharCode(65 + idx)}
                </div>
                <span className={`text-lg font-medium ${answers[currentQuestion] === idx ? 'text-white' : 'text-slate-300'}`}>
                  {opt}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Navigation */}
        <div className="mt-12 flex justify-between items-center">
          <button 
            disabled={currentQuestion === 0} 
            onClick={() => setCurrentQuestion(p => p - 1)} 
            className="px-10 py-4 font-bold text-slate-500 hover:text-white disabled:opacity-0 transition-all"
          >
            ← Back
          </button>
          
          <div className="flex gap-2">
            {questions.map((_, i) => (
              <div key={i} className={`h-1.5 rounded-full transition-all duration-300 ${i === currentQuestion ? 'w-8 bg-indigo-500' : answers[i] !== -1 ? 'w-4 bg-emerald-500' : 'w-2 bg-slate-800'}`} />
            ))}
          </div>

          <button 
            disabled={currentQuestion === questions.length - 1} 
            onClick={() => setCurrentQuestion(p => p + 1)}
            className="bg-indigo-600 hover:bg-indigo-500 text-white px-12 py-4 rounded-2xl font-bold shadow-xl shadow-indigo-500/20 disabled:opacity-30 disabled:pointer-events-none transition-all"
          >
            {currentQuestion === questions.length - 1 ? 'Last Question' : 'Next →'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProfessionalTestEngine;
